### ISSUE TITLE
Ability to copy everything from a source folder to destination path/folder

### ISSUE THREAD

**Issue by sunn-e** [varunsridharan/action-github-workflow-sync#2]
I tried passing the path as traditional "path/to/folder/*" to get every file in a folder but it does not work. This feature can come handy when you have many files in source folder.

**Comment by varunsridharan** [comment]
This feature Added in 2.0

**Comment by wagnst** [comment]
hi @varunsridharan did you test this feature? Actually for me it does not work, when copying a folder. It always says:
```
  terraform=.github/workflows
  	✔  xxx/workflows/terraform => .github/workflows
  Error: 	🛑️  Unable To Copy File.
  Error: no such file or directory: /home/runner/work/yyy/yyy/xxx/workflows/terraform/\.
```
I have a folder with subfolder structure and files that shall be copied by this inside the workflows folder (I do use `composite` feature of actions inside here)

**Comment by varunsridharan** [comment]
@wagnst can you please provide your workflow yaml file ??
Just the workflow copy action's yml will do

**Comment by wagnst** [comment]
@varunsridharan sure, please see here:

where `terraform` is a folder inside the `<ORG name>/workflows` folder (which is in the ROOT of the repo). It shall go into `.github/workflows`. I see in the message its detected correctly, but it seems the `cp` command actually gives the error output.

`terraform` folder has 4 subfolders, where in each subfolder there is one file each called `action.yml`. Its an implementation using the new actions `composite` feature that i would like to sync as well. For composite check here: https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action

```
name: Workflow Sync for landingzone git repositories

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - '<ORG name>/**'
  schedule:
    - cron: "0 0 * * *" # Run at the end of every day
  workflow_dispatch:

env:
  DRY_RUN: false
  TF_WORKSPACE_REPOSITORIES: |
    <ORG name>/base-landingzone
  TF_WORKSPACE_WORKFLOW_FILES: |
    tf-workspace-master.yml
    tf-workspace-pr.yml
    tf-workspace-editorconfig=.editorconfig
    tf-workspace-gitignore=.gitignore
    tf-workspace-CODEOWNERS=.github/CODEOWNERS
    pull_request_template.md=.github/pull_request_template.md
    dependabot.yml=.github/dependabot.yml
    terraform=.github/workflows
jobs:
  github-repo-sync-tf-workspaces:
    name: "File sync for tf workspace repositories"
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.TF_WORKSPACE_REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.TF_WORKSPACE_WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
          PULL_REQUEST: true
          COMMIT_MESSAGE: "Sync of files from <ORG name>/base-landingzone"
```
