### ISSUE TITLE
Add label to PR created by bot

### ISSUE THREAD

**Issue by dmytro-orlenko** [varunsridharan/action-github-workflow-sync#27]
Would be better if I can setup labels for PR created by bot

```
name: Workflow Sync

on:
  push:
    branches:
      - master
env:
  DRY_RUN: false
  CUSTOM_LABEL: workflow_sync_bot
  REPOSITORIES: |
  
  WORKFLOW_FILES: |

jobs:
  Github_Workflow_Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          CUSTOM_LABEL: ${{ env.CUSTOM_LABEL }}

```
