### ISSUE TITLE
Intermittent 'Repository Dose Not Exists !' error whilst trying to sync

### ISSUE THREAD

**Issue by kevinvella1** [varunsridharan/action-github-workflow-sync#9]
**Describe the bug**
Intermittent 'Repository Dose Not Exists !' error whilst trying to sync

**To Reproduce**
1. Run workflow for multiple repositories

**Expected behavior**
Workflows should sync across all repositories

**Additional context**
We have multiple repositories being used for syncing and we are constantly running into the Repository Dose Not Exists ! error. It does not happen all the time but intermittent

**Comment by varunsridharan** [comment]
@kevinvella1 sorry about that. but can you provide more info?

1. is that a private repository ?
2. how often dose this occur for you ?
3. have you tried setting up proper Access Token for it ?

**Comment by afirth** [comment]
This error occurs when the token provided to the action in the input `GITHUB_TOKEN` does not have access to the downstream repos.

**Comment by afirth** [comment]
I can reliably reproduce this by calling the action twice.

```
      - name: Fetching Local Repository
        uses: actions/checkout@master

      - name: Running Workflow Sync - K8s
        # uses: varunsridharan/action-github-workflow-sync@decdb07b953f882d879ffbd4eb82a588842e22b9
        uses: FATMAP/action-github-workflow-sync@cd4f0dbfb282260c1fcad62bd31a6a7c1d00d410
        env:
          REPOSITORIES: |
            FATMAP/search-infra
          WORKFLOW_FILES: |
            github-actions/k8s/.=.github/workflows
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_SYNC_PERSONAL_ACCESS_TOKEN }}
          PULL_REQUEST: true
          COMMIT_EACH_FILE: true

      - name: Running Workflow Sync - K8s
        # uses: varunsridharan/action-github-workflow-sync@decdb07b953f882d879ffbd4eb82a588842e22b9
        uses: FATMAP/action-github-workflow-sync@cd4f0dbfb282260c1fcad62bd31a6a7c1d00d410
        env:
          REPOSITORIES: |
            FATMAP/search-infra
          WORKFLOW_FILES: |
            github-actions/k8s/.=.github/workflows
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_SYNC_PERSONAL_ACCESS_TOKEN }}
          PULL_REQUEST: true
          COMMIT_EACH_FILE: true
```

```
Run FATMAP/action-github-workflow-sync@cd4f0dbfb282260c1fcad62bd31a6a7c1d00d410
-------------------------------------------------------
⚙️ Basic Config
  * AUTO_CREATE_NEW_BRANCH     : false
  * COMMIT_EACH_FILE           : true
  * PULL_REQUEST               : true
  * DRY_RUN                    : true
  * WORKFLOW_FILES_DIR         : workflows
  * WORKSPACE                  : /home/runner/work/workflow-sync/
  * SKIP_CI                    : false
  * COMMIT_MESSAGE             : false
-------------------------------------------------------

📓 FATMAP/search-infra
  ⚙️ Repository Config
  	Slug        : search-infra
  	Owner       : FATMAP
  	Git URL     : ***github.com/FATMAP/search-infra.git
  	Branch      : default
  	Local Path  : /home/runner/work/workflow-sync/FATMAP/search-infra/default/
  	✔  Repository Cloned
  	✔  Pull Request Branch "file-sync-10-master-1622567253" Created From master
  
  🗃 Git Config
  	> Name  : Workflow Sync Bot
  	> Email : githubactionbot+workflowsync@gmail.com
  
  github-actions/k8s/.=.github/workflows
  	✔  github-actions/k8s/. => .github/workflows
  ✔  [file-sync-10-master-1622567253 b010d2e] 💬 - Files Synced | Runner ID : 10 | ⚡ Triggered By FATMAP/github-file-sync
   2 files changed, 135 insertions(+)
   create mode 100644 .github/workflows/kustomize-lint.yaml
   create mode 100644 .github/workflows/skaffold-deploy.yaml
   
  Warning: ⚠️ No Changes Are Pushed
  Git Status
  On branch file-sync-10-master-1622567253
  nothing to commit, working tree clean
   

0s
Run FATMAP/action-github-workflow-sync@cd4f0dbfb282260c1fcad62bd31a6a7c1d00d410
  with:
    DRY_RUN: true
    REPOSITORIES: FATMAP/search-infra
  
    WORKFLOW_FILES: github-actions/k8s/.=.github/workflows
  
    GITHUB_TOKEN: ***
    PULL_REQUEST: true
    COMMIT_EACH_FILE: true
    WORKFLOW_FILES_DIR: workflows
    AUTO_CREATE_NEW_BRANCH: false
    SKIP_CI: false
    COMMIT_MESSAGE: false
  env:
    DRY_RUN: true
    REPOSITORIES: FATMAP/search-infra
  
    WORKFLOW_FILES: github-actions/k8s/.=.github/workflows
  
-------------------------------------------------------
⚙️ Basic Config
  * AUTO_CREATE_NEW_BRANCH     : false
  * COMMIT_EACH_FILE           : true
  * PULL_REQUEST               : true
  * DRY_RUN                    : true
  * WORKFLOW_FILES_DIR         : workflows
  * WORKSPACE                  : /home/runner/work/workflow-sync/
  * SKIP_CI                    : false
  * COMMIT_MESSAGE             : false
-------------------------------------------------------

📓 FATMAP/search-infra
  ⚙️ Repository Config
  	Slug        : search-infra
  	Owner       : FATMAP
  	Git URL     : ***github.com/FATMAP/search-infra.git
  	Branch      : default
  	Local Path  : /home/runner/work/workflow-sync/FATMAP/search-infra/default/
  Error: 	🛑️  Repository Dose Not Exists !
```

Additionally, these errors do not fail the workflow, which they probably should
